#!/bin/bash

gcc_source="https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major"
gcc_dest="tools/gcc-arm-none-eabi-9-2019-q4-major.tar.bz2"
gcc_dir="tools/gcc-arm-none-eabi-9-2019-q4-major"

sdk_source="https://www.nordicsemi.com/-/media/Software-and-other-downloads/SDKs/nRF5-SDK-for-Thread/nRF5-SDK-for-Thread-and-Zigbee/nRF5SDKforThreadandZigbeev400dc7186b.zip"
sdk_dest="tools/nRF5SDKforThreadandZigbeev400dc7186b.zip"

case `uname -s` in
     Linux) gcc_source="$gcc_source-x86_64-linux.tar.bz2";;
    Darwin) gcc_source="$gcc_source-mac.tar.bz2";;
         *) echo "unsupported os"
            exit 1
            ;;
esac

if [ ! -d "$gcc_dir" ]; then

    if [ ! -f "$gcc_dest" ]; then
        curl -o "$gcc_dest" "$gcc_source"
    fi

    tar -C "tools" -xvf "$gcc_dest"

    rm "$gcc_dest"

fi

if [ ! -d "$sdk_dir" ]; then

    if [ ! -f "$sdk_dest" ]; then
        curl -o "$sdk_dest" "$sdk_source"
    fi

    unzip "$sdk_dest" -d "sdk"

    rm "$sdk_dest"

fi
